### ISSUE TITLE
Advice on how/where to add extra ffmpeg filters

### ISSUE THREAD

**Issue by oilytin** [Twinklebear/fbed#3]
script works great! just looking to add a frame rate filter.
could you offer any pointers?
I found the following example in the ffmpeg-python documentation but i am unsure how to apply it to your code
(
    ffmpeg
    .input('dummy.mp4')
    .filter('fps', fps=25, round='up')
    .output('dummy2.mp4')
    .run()
)
Any help would be appreciated
Regards
Anthony

**Comment by Twinklebear** [comment]
Thanks! I think you can chain more filters on here after the pix fmt filter: https://github.com/Twinklebear/fbed/blob/main/fbed.py#L89 . So It'd be like:

```python
video = in_stream.video.filter("format", **{"pix_fmts": "yuv420p"}).filter("fps", fps=25, round="up") # etc..
```

**Comment by oilytin** [comment]
Thanks for the help. it works perfectly!
